// src/lib/HexFloat/HexFloat.svelte
<script lang="ts">
  import { onMount, tick } from "svelte";

  import {
    createHexFloat,
    supportsHtmlInCanvas,
    type HexFloatInstance,
    type HexFloatOptions,
  } from "./HexFloatVanilla";

  interface Props extends HexFloatOptions {
    class?: string;
    children?: import("svelte").Snippet;
  }

  let { class: className = "", children, ...options }: Props = $props();

  let sourceEl = $state<HTMLCanvasElement>()!;
  let contentEl = $state<HTMLDivElement>()!;
  let outputEl = $state<HTMLCanvasElement>()!;
  let native = $state(false);
  let instance: HexFloatInstance | null = null;

  onMount(() => {
    native = supportsHtmlInCanvas();
    let disposed = false;
    tick().then(() => {
      if (disposed) return;
      instance = createHexFloat(
        { source: sourceEl, content: contentEl, output: outputEl },
        options,
      );
      if (native && !instance) native = false;
    });
    return () => {
      disposed = true;
      instance?.destroy();
      instance = null;
    };
  });

  $effect(() => {
    instance?.setOptions({ ...options });
  });
</script>

<div class={className} style="position: relative;">
  <canvas
    bind:this={sourceEl}
    layoutsubtree="true"
    style={native
      ? "position: absolute; inset: 0; width: 100%; height: 100%;"
      : "display: none;"}
  >
    {#if native}
      <div
        bind:this={contentEl}
        style="position: relative; width: 100%; height: 100%; overflow: auto;"
      >
        {@render children?.()}
      </div>
    {/if}
  </canvas>
  {#if !native}
    <div
      bind:this={contentEl}
      style="position: relative; width: 100%; height: 100%; overflow: auto;"
    >
      {@render children?.()}
    </div>
  {/if}
  <canvas
    bind:this={outputEl}
    aria-hidden="true"
    style="position: absolute; inset: 0; width: 100%; height: 100%; pointer-events: none;"
  ></canvas>
</div>

// src/lib/HexFloat/HexFloat.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";

import {
  createHexFloat,
  supportsHtmlInCanvas,
  type HexFloatInstance,
  type HexFloatOptions,
} from "./HexFloatVanilla";

const props = defineProps<HexFloatOptions>();

const sourceEl = ref<HTMLCanvasElement | null>(null);
const contentEl = ref<HTMLDivElement | null>(null);
const outputEl = ref<HTMLCanvasElement | null>(null);
const native = ref(false);

let instance: HexFloatInstance | null = null;
let raf = 0;

onMounted(() => {
  native.value = supportsHtmlInCanvas();
  raf = requestAnimationFrame(() => {
    if (sourceEl.value && contentEl.value && outputEl.value) {
      instance = createHexFloat(
        {
          source: sourceEl.value,
          content: contentEl.value,
          output: outputEl.value,
        },
        props,
      );
      if (native.value && !instance) native.value = false;
    }
  });
});

onBeforeUnmount(() => {
  cancelAnimationFrame(raf);
  instance?.destroy();
  instance = null;
});

watch(
  () => ({ ...props }),
  (next) => instance?.setOptions(next),
  { deep: true },
);
</script>

<template>
  <div style="position: relative">
    <canvas
      ref="sourceEl"
      layoutsubtree="true"
      :style="
        native
          ? 'position: absolute; inset: 0; width: 100%; height: 100%'
          : 'display: none'
      "
    >
      <div
        v-if="native"
        ref="contentEl"
        style="position: relative; width: 100%; height: 100%; overflow: auto"
      >
        <slot />
      </div>
    </canvas>
    <div
      v-if="!native"
      ref="contentEl"
      style="position: relative; width: 100%; height: 100%; overflow: auto"
    >
      <slot />
    </div>
    <canvas
      ref="outputEl"
      aria-hidden="true"
      style="
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        pointer-events: none;
      "
    />
  </div>
</template>
