// src/lib/Peel/Peel.preact.tsx
import { useEffect, useRef, useState, useCallback } from "preact/hooks";
import type { JSX } from "preact";
import { type ComponentChildren } from "preact";

import {
  createPeel,
  supportsHtmlInCanvas,
  type PeelInstance,
  type PeelOptions,
} from "./PeelVanilla";

function useSyncExternalStore<T>(
  subscribe: (onStoreChange: () => void) => () => void,
  getSnapshot: () => T,
): T {
  const [value, setValue] = useState(getSnapshot);
  useEffect(() => {
    const unsubscribe = subscribe(() => setValue(getSnapshot()));
    return unsubscribe;
  }, []);
  return value;
}

export interface PeelProps extends PeelOptions {
  /** The content that peels away. */
  children: ComponentChildren;
  /** The content revealed underneath the peel. */
  under?: ComponentChildren;
  className?: string;
  style?: JSX.CSSProperties;
}

const emptySubscribe = () => () => {};

export function Peel({
  children,
  under,
  className,
  style,
  ...options
}: PeelProps) {
  const sourceRef = useRef<HTMLCanvasElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const outputRef = useRef<HTMLCanvasElement>(null);
  const underRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<PeelInstance | null>(null);
  const [initialOptions] = useState(options);
  const [failed, setFailed] = useState(false);

  const supported = useSyncExternalStore(
    emptySubscribe,
    supportsHtmlInCanvas,
  );
  const native = supported && !failed;

  useEffect(() => {
    const source = sourceRef.current;
    const content = contentRef.current;
    const output = outputRef.current;
    if (!source || !content || !output) return;
    instanceRef.current = createPeel(
      { source, content, output, under: underRef.current ?? undefined },
      initialOptions,
    );
    if (native && !instanceRef.current) setFailed(true);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions, native]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  const sourceCallbackRef = useCallback((el: HTMLCanvasElement | null) => {
    sourceRef.current = el;
    if (el) el.setAttribute("layoutsubtree", "true");
  }, []);

  return (
    <div className={className} style={{ position: "relative", ...(style as any) }}>
      {native ? (
        <div
          ref={underRef}
          style={{
            position: "absolute",
            inset: 0,
            overflow: "hidden",
            visibility: "hidden",
          }}
        >
          {under as any}
        </div>
      ) : null}
      <canvas
        ref={sourceCallbackRef}
        style={
          native
            ? {
                position: "absolute",
                inset: 0,
                width: "100%",
                height: "100%",
                pointerEvents: "none",
              }
            : { display: "none" }
        }
      >
        {native ? (
          <div
            ref={contentRef}
            style={{
              position: "relative",
              width: "100%",
              height: "100%",
              overflow: "hidden",
              pointerEvents: "auto",
            }}
          >
            {children as any}
          </div>
        ) : null}
      </canvas>
      {!native ? (
        <div
          ref={contentRef}
          style={{
            position: "relative",
            width: "100%",
            height: "100%",
            overflow: "hidden",
          }}
        >
          {children as any}
        </div>
      ) : null}
      <canvas
        ref={outputRef}
        aria-hidden
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          pointerEvents: "none",
        }}
      />
    </div>
  );
}

export type { PeelInstance, PeelOptions };

export default Peel;

// src/lib/Peel/Peel.svelte
<script lang="ts">
  import { onMount, tick } from "svelte";

  import {
    createPeel,
    supportsHtmlInCanvas,
    type PeelInstance,
    type PeelOptions,
  } from "./PeelVanilla";

  interface Props extends PeelOptions {
    class?: string;
    children?: import("svelte").Snippet;
    under?: import("svelte").Snippet;
  }

  let { class: className = "", children, under, ...options }: Props = $props();

  let sourceEl = $state<HTMLCanvasElement>()!;
  let contentEl = $state<HTMLDivElement>()!;
  let outputEl = $state<HTMLCanvasElement>()!;
  let underEl = $state<HTMLDivElement>();
  let native = $state(false);
  let instance: PeelInstance | null = null;

  onMount(() => {
    native = supportsHtmlInCanvas();
    let disposed = false;
    tick().then(() => {
      if (disposed) return;
      instance = createPeel(
        { source: sourceEl, content: contentEl, output: outputEl, under: underEl },
        options,
      );
      if (native && !instance) native = false;
    });
    return () => {
      disposed = true;
      instance?.destroy();
      instance = null;
    };
  });

  $effect(() => {
    instance?.setOptions({ ...options });
  });
</script>

<div class={className} style="position: relative;">
  {#if native}
    <div
      bind:this={underEl}
      style="position: absolute; inset: 0; overflow: hidden; visibility: hidden;"
    >
      {@render under?.()}
    </div>
  {/if}
  <canvas
    bind:this={sourceEl}
    layoutsubtree="true"
    style={native
      ? "position: absolute; inset: 0; width: 100%; height: 100%; pointer-events: none;"
      : "display: none;"}
  >
    {#if native}
      <div
        bind:this={contentEl}
        style="position: relative; width: 100%; height: 100%; overflow: hidden; pointer-events: auto;"
      >
        {@render children?.()}
      </div>
    {/if}
  </canvas>
  {#if !native}
    <div
      bind:this={contentEl}
      style="position: relative; width: 100%; height: 100%; overflow: hidden;"
    >
      {@render children?.()}
    </div>
  {/if}
  <canvas
    bind:this={outputEl}
    aria-hidden="true"
    style="position: absolute; inset: 0; width: 100%; height: 100%; pointer-events: none;"
  ></canvas>
</div>
